config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    get 'welcome/index'

    root 'welcome#index'
    resources :post_tables do
      resources :comments
    end
    resources :user_tables
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post_table
end

app/models/post_table.rb
class PostTable < ApplicationRecord
  has_many :comments
  def self.search(search)
    where("title LIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_table.rb
class UserTable < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = PostTable.find(params[:post_table_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_table_path(@post)
  end

  def destroy
    @post = PostTable.find(params[:post_table_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_table_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/post_tables_controller.rb
class PostTablesController < ApplicationController
  before_action :set_post_table, only: [:show, :edit, :update, :destroy]

  # GET /post_tables
  # GET /post_tables.json
  def index
    @post_tables = PostTable.all

    if params[:search]
      @post_tables = PostTable.search(params[:search]).order("created_at DESC")
    else
      @post_tables = PostTable.all.order("created_at DESC")
    end
  end

  # GET /post_tables/1
  # GET /post_tables/1.json
  def show
  end

  # GET /post_tables/new
  def new
    @post_table = PostTable.new
  end

  # GET /post_tables/1/edit
  def edit
  end

  # POST /post_tables
  # POST /post_tables.json
  def create
    @post_table = PostTable.new(post_table_params)

    respond_to do |format|
      if @post_table.save
        format.html { redirect_to @post_table, notice: 'Post table was successfully created.' }
        format.json { render :show, status: :created, location: @post_table }
      else
        format.html { render :new }
        format.json { render json: @post_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_tables/1
  # PATCH/PUT /post_tables/1.json
  def update
    respond_to do |format|
      if @post_table.update(post_table_params)
        format.html { redirect_to @post_table, notice: 'Post table was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_table }
      else
        format.html { render :edit }
        format.json { render json: @post_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_tables/1
  # DELETE /post_tables/1.json
  def destroy
    @post_table.destroy
    respond_to do |format|
      format.html { redirect_to post_tables_url, notice: 'Post table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_table
      @post_table = PostTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_table_params
      params.require(:post_table).permit(:title, :content)
    end
end

app/controllers/user_tables_controller.rb
class UserTablesController < ApplicationController
  before_action :set_user_table, only: [:show, :edit, :update, :destroy]

  # GET /user_tables
  # GET /user_tables.json
  def index
    @user_tables = UserTable.all
  end

  # GET /user_tables/1
  # GET /user_tables/1.json
  def show
  end

  # GET /user_tables/new
  def new
    @user_table = UserTable.new
  end

  # GET /user_tables/1/edit
  def edit
  end

  # POST /user_tables
  # POST /user_tables.json
  def create
    @user_table = UserTable.new(user_table_params)

    respond_to do |format|
      if @user_table.save
        format.html { redirect_to @user_table, notice: 'User table was successfully created.' }
        format.json { render :show, status: :created, location: @user_table }
      else
        format.html { render :new }
        format.json { render json: @user_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_tables/1
  # PATCH/PUT /user_tables/1.json
  def update
    respond_to do |format|
      if @user_table.update(user_table_params)
        format.html { redirect_to @user_table, notice: 'User table was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_table }
      else
        format.html { render :edit }
        format.json { render json: @user_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_tables/1
  # DELETE /user_tables/1.json
  def destroy
    @user_table.destroy
    respond_to do |format|
      format.html { redirect_to user_tables_url, notice: 'User table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_table
      @user_table = UserTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_table_params
      params.require(:user_table).permit(:user_name, :user_pass, :user_mail)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_tables_helper.rb
module PostTablesHelper
end

app/helpers/thread1_helper.rb
module Thread1Helper
end

app/helpers/user_tables_helper.rb
module UserTablesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to 'Destroy Comment', [comment.post_table, comment],
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' } %>
  </p>

app/views/comments/_form.html.erb
<%= form_for([@post_table, @post_table.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %>
    <%= f.text_field :commenter %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div id="usrCont">
    <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/post_tables/_form.html.erb
<%= form_for(post_table) do |f| %>
  <% if post_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_table.errors.count, "error") %> prohibited this post_table from being saved:</h2>

      <ul>
      <% post_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, :rows => "4", :cols => "50" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_tables/edit.html.erb
<h1>Editing Post Table</h1>

<%= render 'form', post_table: @post_table %>

<%= link_to 'Show', @post_table %> |
<%= link_to 'Back', post_tables_path %>

app/views/post_tables/index.html.erb
<p id="notice"><%= notice %></p>

<header>
<h1>>General Discussion</h1>
</header>

<div id="search">
<%= form_tag(post_tables_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Post" %>
    <%= submit_tag "Search", :title => nil, :id => "srchBtn" %>
    <!--<h4>Please enter search term!</h4>-->
<% end %>
</div>
<% if @post_tables.blank? %>
  <h4>There are no matching posts to: <%= params[:search] %>.</h4>
<% elsif params[:search].blank? %>
  <h4>Please enter search term!</h4>
<% end %>

<table>
  <tbody>
    <% @post_tables.each do |post_table| %>
      <tr>
        <div id="center">
        <div id="contCont">
        <p id="titleContent"><%= post_table.title %></p>
        <div id="postContentCont"><p id="postContent"><%= post_table.content %></p></div>
        <div id="manage">
        <p><%= link_to 'Show', post_table %></p>
        <p><%= link_to 'Edit', edit_post_table_path(post_table) %></p>
        <p id="dest"><%= link_to 'Destroy', post_table, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        </div>
        </div>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="navCont">
<nav>
<%= link_to 'Back to Index', root_path, :id => "backTo", :class => "navi" %>
<%= link_to 'New Post', new_post_table_path, :id =>"newP", :class => "navi" %>
</nav>
</div>

<footer>
    <p>This is a footer that contains legal information</p>
</footer>

app/views/post_tables/new.html.erb
<h1>New Post Table</h1>

<%= render 'form', post_table: @post_table %>

<%= link_to 'Back', post_tables_path %>

app/views/post_tables/show.html.erb
<h1><%= @post_table.title %></h1>

<br>

<p><%= @post_table.content %></p>

<br>
<h2> Comments <h2>
  <%= render @post_table.comments %>

<h2> Add a comment<h2>
 <%= render 'comments/form' %>

<%= link_to 'Edit', edit_post_table_path(@post_table) %> |
<%= link_to 'Back', post_tables_path %>

app/views/user_tables/_form.html.erb
<%= form_for(user_table) do |f| %>
  <% if user_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_table.errors.count, "error") %> prohibited this user_table from being saved:</h2>

      <ul>
      <% user_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>

  <div class="field">
    <%= f.label :user_pass %>
    <%= f.text_field :user_pass %>
  </div>

  <div class="field">
    <%= f.label :user_mail %>
    <%= f.text_field :user_mail %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_tables/edit.html.erb
<h1>Editing User Table</h1>

<%= render 'form', user_table: @user_table %>

<%= link_to 'Show', @user_table %> |
<%= link_to 'Back', user_tables_path %>

app/views/user_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Tables</h1> 

<tbody>
    <% @user_tables.each do |user_table| %>
    <tr>
        <td><%= user_table.user_name %></td>
        <td><%= user_table.user_pass %></td>
        <td><%= user_table.user_mail %></td>
        <td><%= link_to 'Show', user_table %></td>
        <td><%= link_to 'Edit', edit_user_table_path(user_table) %></td>
        <td><%= link_to 'Destroy', user_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</tbody>

<br>
<br>

<%= link_to 'New User Table', new_user_table_path %>

app/views/user_tables/new.html.erb
<h1>New User Table</h1>

<%= render 'form', user_table: @user_table %>

<%= link_to 'Back', user_tables_path %>

app/views/user_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @user_table.user_name %>
</p>

<p>
  <strong>User pass:</strong>
  <%= @user_table.user_pass %>
</p>

<p>
  <strong>User mail:</strong>
  <%= @user_table.user_mail %>
</p>

<%= link_to 'Edit', edit_user_table_path(@user_table) %> |
<%= link_to 'Back', user_tables_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="">
<head>
    <meta charset="utf-8">
    <title></title>
</head>

<body>
    <header>
    <h1>>Forum start page</h1>
        <p>Sample text forum</p>
    </header>
    <div id="thrdCont">
    <ul>
        <%= link_to '>General', post_tables_path, :id => "general"%>
        <p>This thread contains a general discussion</p>
    </ul>
    </div>
    
    <footer>
        <p>This is a footer that contains legal information</p>
    </footer>
</body>
</html>